# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-01 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLoginDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify', models.BooleanField(default=False)),
                ('signedUpWithFB', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank='noCategoryName', max_length=25)),
                ('parentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('amount', models.PositiveSmallIntegerField()),
                ('securityDeposit', models.PositiveIntegerField()),
                ('finePaid', models.DecimalField(decimal_places=1, max_digits=4)),
                ('transactionDate', models.DateField()),
                ('status', models.PositiveSmallIntegerField()),
                ('address', models.CharField(default='noAddress', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lenderRating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('borrowerRating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('numberOfLenderRating', models.PositiveSmallIntegerField(default=0)),
                ('numberOfBorrowerRating', models.PositiveSmallIntegerField(default=0)),
                ('favourites', models.CharField(default='noFavourites', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='noName', max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('passwd', models.CharField(default='noPasswd', max_length=30)),
                ('phNo', models.CharField(default='noNumber', max_length=13)),
                ('address', models.CharField(default='noAddress', max_length=100)),
                ('pincode', models.CharField(default='noCode', max_length=7)),
                ('joinedOn', models.DateField()),
                ('genderIsMale', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='noName', max_length=20)),
                ('description', models.CharField(default='noDescription', max_length=160)),
                ('amount', models.PositiveSmallIntegerField()),
                ('securityDeposit', models.PositiveIntegerField()),
                ('addedDate', models.DateField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Category')),
                ('lender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PersonalInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewBy', models.PositiveIntegerField(verbose_name=main.models.PersonalInfo)),
                ('star', models.DecimalField(decimal_places=0, max_digits=1)),
                ('comment', models.TextField(default='noComment')),
                ('uploadDate', models.DateField()),
                ('numberOfUpvotes', models.PositiveSmallIntegerField()),
                ('forBorrower', models.BooleanField(default=False)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Orders')),
                ('reviewFor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PersonalInfo')),
            ],
        ),
        migrations.CreateModel(
            name='votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voteIsUpvote', models.BooleanField(default=True)),
                ('personalInfoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PersonalInfo')),
                ('reviewId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Reviews')),
            ],
        ),
        migrations.AddField(
            model_name='personalactivity',
            name='personalInfoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PersonalInfo'),
        ),
        migrations.AddField(
            model_name='orders',
            name='borrower_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PersonalInfo'),
        ),
        migrations.AddField(
            model_name='orders',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product'),
        ),
        migrations.AddField(
            model_name='accountlogindetails',
            name='personalInfoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PersonalInfo'),
        ),
    ]
